version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    #expose:
    #  - 5432
    ports:
      - "5444:5432"
    #volumes:
    #  - ./db_dump/galaxy_dump.sql:/docker-entrypoint-initdb.d/dummy_dump.sql

  mysite:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - static_volume:/site/static

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - mysite


volumes:
  static_volume: