# Generated by Django 4.1.7 on 2023-02-25 17:11

import content_for_evrbd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrittishBulldog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('year', models.CharField(max_length=255, verbose_name='Year')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.ImageField(upload_to=content_for_evrbd.models.content_file_name)),
            ],
        ),
    ]
