# Generated by Django 4.1.7 on 2023-03-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_for_evrbd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
