# Generated by Django 4.1.7 on 2023-02-26 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content_for_evrbd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brittishbulldog',
            options={'ordering': ['year', 'classes']},
        ),
        migrations.RemoveField(
            model_name='brittishbulldog',
            name='title',
        ),
        migrations.AddField(
            model_name='brittishbulldog',
            name='classes',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Class'),
            preserve_default=False,
        ),
    ]
