# Generated by Django 4.1.7 on 2023-02-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_for_evrbd', '0002_alter_brittishbulldog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brittishbulldog',
            name='slug',
        ),
    ]
