# Generated by Django 4.1.7 on 2023-02-26 14:51

import content_for_evrbd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_for_evrbd', '0003_remove_brittishbulldog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brittishbulldog',
            name='content',
            field=models.FileField(upload_to=content_for_evrbd.models.content_file_name),
        ),
    ]
