# Generated by Django 4.1.7 on 2023-03-05 04:41

import content_for_evrbd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_for_evrbd', '0004_alter_brittishbulldog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='brittishbulldog',
            name='audio',
            field=models.FileField(blank=True, upload_to=content_for_evrbd.models.content_file_name),
        ),
    ]
