# Generated by Django 4.1.7 on 2024-04-15 11:34

import content_for_evrbd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_for_evrbd', '0007_britishbulldog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, verbose_name='Year')),
                ('stage', models.CharField(choices=[('School stage', 'School stage'), ('Municipal stage', 'Municipal stage'), ('Region stage', 'Region stage'), ('Final stage', 'Final stage')], max_length=255, verbose_name='Stage')),
                ('classes', models.CharField(max_length=255, verbose_name='Class')),
                ('task', models.FileField(upload_to=content_for_evrbd.models.content_file_name_olymp)),
                ('answer', models.FileField(blank=True, upload_to=content_for_evrbd.models.content_file_name_olymp)),
                ('audio', models.FileField(blank=True, upload_to=content_for_evrbd.models.content_file_name_olymp)),
                ('script', models.FileField(blank=True, upload_to=content_for_evrbd.models.content_file_name_olymp)),
                ('order', models.IntegerField(verbose_name='Order')),
            ],
            options={
                'ordering': ['year', 'stage'],
            },
        ),
    ]
