# Generated by Django 4.1.7 on 2024-04-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_for_evrbd', '0008_olympway'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OlympWay',
        ),
    ]
