# Generated by Django 4.1.7 on 2024-05-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_for_evrbd', '0010_olympway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympway',
            name='order',
        ),
        migrations.AddField(
            model_name='olympway',
            name='classes_order',
            field=models.IntegerField(default=1, verbose_name='classes_order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='olympway',
            name='stage_order',
            field=models.IntegerField(default='1', verbose_name='stage_order'),
            preserve_default=False,
        ),
    ]
