# Generated by Django 4.1.7 on 2025-01-14 08:13

import content_for_evrbd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_for_evrbd', '0011_remove_olympway_order_olympway_classes_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=content_for_evrbd.models.content_tutorial_name)),
                ('category', models.CharField(choices=[('Articles', 'Articles'), ('Lessons', 'Lessons'), ('Methodological', 'Methodological'), ('Presentations', 'Presentations'), ('Materials', 'Materials')], max_length=255, verbose_name='Part of exam')),
            ],
        ),
    ]
