# Generated by Django 4.1.7 on 2025-01-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_for_evrbd', '0012_tutorialfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialfile',
            name='category',
            field=models.CharField(choices=[('Articles', 'Articles'), ('Lessons', 'Lessons'), ('Methodological guidelines', 'Methodological guidelines'), ('Classroom presentations', 'Classroom presentations'), ('Teaching materials', 'Teaching materials')], max_length=255, verbose_name='Category'),
        ),
    ]
