# Generated by Django 4.1.7 on 2023-03-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0006_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
