# Generated by Django 4.1.7 on 2023-03-09 15:46

from django.db import migrations, models
import galaxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0007_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, verbose_name='Year')),
                ('stage', models.CharField(choices=[('School stage', 'School stage'), ('Municipal stage', 'Municipal stage'), ('Region stage', 'Region stage'), ('Final stage', 'Final stage')], max_length=255, verbose_name='Stage')),
                ('classes', models.CharField(max_length=255, verbose_name='Class')),
                ('task', models.FileField(upload_to=galaxy.models.content_file_name_test)),
                ('answer', models.FileField(blank=True, upload_to=galaxy.models.content_file_name_test)),
                ('audio', models.FileField(blank=True, upload_to=galaxy.models.content_file_name_test)),
                ('script', models.FileField(blank=True, upload_to=galaxy.models.content_file_name_test)),
            ],
            options={
                'ordering': ['year', 'stage'],
            },
        ),
    ]
