# Generated by Django 4.1.7 on 2023-03-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0008_olympway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Type of exam')),
                ('part', models.CharField(max_length=255, verbose_name='Part of exam')),
            ],
            options={
                'ordering': ['type', 'part'],
            },
        ),
    ]
