# Generated by Django 4.1.7 on 2023-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0009_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='test_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
