# Generated by Django 4.1.7 on 2023-03-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0013_questions_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
