# Generated by Django 4.1.7 on 2023-03-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0014_questions_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_number',
            field=models.PositiveIntegerField(),
        ),
    ]
