# Generated by Django 4.1.7 on 2023-03-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0016_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[(None, 'Choose role'), ('Student', 'Student'), ('Teacher', 'Teacher')], max_length=100),
        ),
    ]
