# Generated by Django 4.1.7 on 2023-03-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0023_alter_results_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='test',
            new_name='test_id',
        ),
    ]
