# Generated by Django 4.1.7 on 2023-03-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0024_rename_test_questions_test_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='test',
            new_name='test_id',
        ),
    ]
