# Generated by Django 4.1.7 on 2023-03-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0025_rename_question_answers_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='match',
            field=models.CharField(default='single_choice_type', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('single_choice_type', 'single_choice_type'), ('match_type', 'match_type'), ('input_type', 'input_type')], default='single_choice_type', max_length=255, verbose_name='Type of question'),
            preserve_default=False,
        ),
    ]
