# Generated by Django 4.1.7 on 2023-03-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0026_answers_match_questions_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='match',
        ),
        migrations.AddField(
            model_name='answers',
            name='addition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(),
        ),
    ]
