# Generated by Django 4.1.7 on 2023-03-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0028_answers_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='addition',
            field=models.TextField(default='None'),
        ),
    ]
