# Generated by Django 4.1.7 on 2023-03-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0029_alter_answers_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='time_limit',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
