# Generated by Django 4.1.7 on 2023-03-27 17:48

from django.db import migrations, models
import galaxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0030_tests_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='media',
            field=models.FileField(blank=True, upload_to=galaxy.models.content_file_name_test),
        ),
        migrations.AlterField(
            model_name='olympway',
            name='answer',
            field=models.FileField(blank=True, upload_to=galaxy.models.content_file_name_olymp),
        ),
        migrations.AlterField(
            model_name='olympway',
            name='audio',
            field=models.FileField(blank=True, upload_to=galaxy.models.content_file_name_olymp),
        ),
        migrations.AlterField(
            model_name='olympway',
            name='script',
            field=models.FileField(blank=True, upload_to=galaxy.models.content_file_name_olymp),
        ),
        migrations.AlterField(
            model_name='olympway',
            name='task',
            field=models.FileField(upload_to=galaxy.models.content_file_name_olymp),
        ),
    ]
