# Generated by Django 4.1.7 on 2023-03-29 11:58

from django.db import migrations, models
import django.db.models.deletion
import galaxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0031_tests_media_alter_olympway_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('media', models.FileField(blank=True, upload_to=galaxy.models.content_file_name_test)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.tests')),
            ],
        ),
    ]
