# Generated by Django 4.1.7 on 2023-03-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0033_remove_tests_media_questions_chapter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chapters',
            name='text_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
