# Generated by Django 4.1.7 on 2023-03-31 09:57

from django.db import migrations, models
import galaxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0034_chapters_info_chapters_text_name_alter_chapters_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='media',
            field=models.FileField(blank=True, upload_to=galaxy.models.content_file_name_test),
        ),
        migrations.AddField(
            model_name='tests',
            name='test_info',
            field=models.TextField(default='Текст, который выводится перед началом теста'),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='media',
            field=models.FileField(blank=True, upload_to=galaxy.models.content_file_name_chapter),
        ),
    ]
