# Generated by Django 4.1.7 on 2023-03-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0035_tests_media_tests_test_info_alter_chapters_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='start_time',
            field=models.FloatField(default=0),
        ),
    ]
