# Generated by Django 4.1.7 on 2023-03-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0036_tests_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='addition',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
