# Generated by Django 4.1.7 on 2023-04-04 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0037_questions_addition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('single_choice_type', 'single_choice_type'), ('match_type', 'match_type'), ('input_type', 'input_type'), ('true_false_type', 'true_false_type')], max_length=255, verbose_name='Type of question'),
        ),
        migrations.CreateModel(
            name='TestTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(default=0)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.tests')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
