# Generated by Django 4.1.7 on 2023-04-07 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import galaxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0038_remove_tests_start_time_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('single_choice_type', 'single_choice_type'), ('match_type', 'match_type'), ('input_type', 'input_type'), ('true_false_type', 'true_false_type'), ('file_adding_type', 'file_adding_type')], max_length=255, verbose_name='Type of question'),
        ),
        migrations.CreateModel(
            name='TasksToCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media1', models.FileField(blank=True, upload_to=galaxy.models.content_file_name_check)),
                ('media2', models.FileField(blank=True, upload_to=galaxy.models.content_file_name_check)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.tests')),
            ],
        ),
    ]
