# Generated by Django 4.1.7 on 2023-04-07 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0042_taskstocheck_is_checked_alter_results_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstocheck',
            name='question_id',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='galaxy.questions'),
            preserve_default=False,
        ),
    ]
