# Generated by Django 4.1.7 on 2023-04-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0043_taskstocheck_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstocheck',
            name='points',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
