# Generated by Django 4.1.7 on 2023-04-08 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0044_taskstocheck_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstocheck',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='taskstocheck',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='taskstocheck',
            name='test_id',
        ),
        migrations.CreateModel(
            name='TestsToCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.tests')),
            ],
        ),
    ]
