# Generated by Django 4.1.7 on 2023-04-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0045_remove_taskstocheck_is_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstocheck',
            name='test_to_check_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='galaxy.teststocheck'),
            preserve_default=False,
        ),
    ]
