# Generated by Django 4.1.7 on 2023-04-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0047_results_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_num',
            field=models.PositiveIntegerField(),
        ),
    ]
