# Generated by Django 4.1.7 on 2023-04-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0048_customuser_is_email_verified_alter_tests_test_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_confirmed',
            field=models.BooleanField(),
        ),
    ]
