# Generated by Django 4.1.7 on 2023-04-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0049_alter_customuser_is_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='test_info',
            new_name='test_details',
        ),
    ]
