# Generated by Django 4.1.7 on 2023-04-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0051_questions_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='date_of_assessment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tests',
            name='is_appointed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tests',
            name='is_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tests',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
