# Generated by Django 4.1.7 on 2023-04-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0052_tests_date_of_assessment_tests_is_appointed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='is_exam',
            new_name='is_assessment',
        ),
    ]
