# Generated by Django 4.1.7 on 2023-05-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0054_groups_customuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='addition_position',
            field=models.CharField(blank=True, choices=[(None, 'Choose position'), (0, 'Before answer'), (1, 'After answer')], max_length=50),
        ),
    ]
