# Generated by Django 4.1.7 on 2023-05-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0055_questions_addition_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='addition',
            new_name='addition_after',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='addition_position',
        ),
        migrations.AddField(
            model_name='questions',
            name='addition_before',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
