# Generated by Django 4.1.7 on 2023-05-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0056_rename_addition_questions_addition_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='test_type',
            field=models.CharField(choices=[('GSE', 'GSE'), ('USE', 'USE')], default='GSE', max_length=255, verbose_name='Type of exam'),
            preserve_default=False,
        ),
    ]
