# Generated by Django 4.1.7 on 2023-05-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0057_groups_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.groups')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.tests')),
            ],
        ),
        migrations.AddField(
            model_name='tests',
            name='groups',
            field=models.ManyToManyField(through='galaxy.Assessments', to='galaxy.groups'),
        ),
    ]
