# Generated by Django 4.1.7 on 2023-05-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0058_remove_tests_date_of_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='used_in_groups',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
