# Generated by Django 4.1.7 on 2023-05-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0059_remove_tests_date_of_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='date_of_assessment',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='is_appointed',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='is_used',
        ),
    ]
