# Generated by Django 4.1.7 on 2023-05-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0060_remove_tests_date_of_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='groups',
        ),
    ]
