# Generated by Django 4.1.7 on 2023-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0061_remove_tests_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='groups',
            field=models.ManyToManyField(through='galaxy.Assessments', to='galaxy.groups'),
        ),
    ]
