# Generated by Django 4.1.7 on 2023-06-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0066_assessments_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assessments_passed',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
