# Generated by Django 4.1.7 on 2023-08-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0067_customuser_assessments_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststocheck',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
