# Generated by Django 4.1.7 on 2023-09-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0068_teststocheck_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='used_in_groups',
            field=models.TextField(),
        ),
    ]
