# Generated by Django 4.1.7 on 2023-10-02 22:46

from django.db import migrations, models
import galaxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0069_alter_tests_used_in_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='media',
            field=models.FileField(blank=True, upload_to=galaxy.models.content_file_name_question),
        ),
    ]
