# Generated by Django 4.1.7 on 2023-10-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0070_questions_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='writing_after',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='questions',
            name='writing_before',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='questions',
            name='writing_fl',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='writing_from',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='writing_letter',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='questions',
            name='writing_subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='writing_to',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
