# Generated by Django 4.1.7 on 2023-10-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0071_questions_writing_after_questions_writing_before_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='writing_before',
        ),
        migrations.AlterField(
            model_name='questions',
            name='writing_fl',
            field=models.CharField(choices=[('letter', 'letter'), ('essay', 'essay')], max_length=255, verbose_name='Type of question'),
        ),
    ]
