# Generated by Django 4.1.7 on 2023-10-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0073_questions_text_questions_text_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='preparation_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
