# Generated by Django 4.1.7 on 2023-10-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0074_questions_preparation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='preparation_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
