# Generated by Django 4.1.7 on 2024-01-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0076_alter_taskstocheck_media1_alter_taskstocheck_media2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='preparation_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
