# Generated by Django 4.1.7 on 2024-02-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0078_questions_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='time_limit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
