# Generated by Django 4.1.7 on 2024-03-20 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0081_alter_results_student_id_alter_results_test_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='assessments_passed',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='used_in_groups',
        ),
        migrations.CreateModel(
            name='UserToAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.assessments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsedTestsToGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.groups')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.tests')),
            ],
        ),
    ]
