# Generated by Django 4.1.7 on 2024-04-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0083_tests_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='media',
        ),
    ]
