# Generated by Django 4.1.7 on 2024-04-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0084_remove_chapters_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympway',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
            preserve_default=False,
        ),
    ]
