# Generated by Django 4.1.7 on 2024-04-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0085_olympway_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OlympWay',
        ),
    ]
