# Generated by Django 4.1.7 on 2024-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0086_delete_olympway'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='trial_test',
            field=models.BooleanField(default=False),
        ),
    ]
