# Generated by Django 4.1.7 on 2024-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0087_tests_trial_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessments',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
