# Generated by Django 4.1.7 on 2024-05-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0088_assessments_is_opened'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadAndLearnTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=255, verbose_name='Type of exam')),
            ],
        ),
        migrations.AlterField(
            model_name='chapters',
            name='test_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galaxy.tests'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='test_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galaxy.tests'),
        ),
        migrations.AddField(
            model_name='chapters',
            name='read_and_learn_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galaxy.readandlearntest'),
        ),
        migrations.AddField(
            model_name='questions',
            name='read_and_learn_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galaxy.readandlearntest'),
        ),
    ]
