# Generated by Django 4.1.7 on 2024-05-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0089_readandlearntest_alter_chapters_test_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readandlearntest',
            name='test_num',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
