# Generated by Django 4.1.7 on 2024-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0090_readandlearntest_test_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='writing_fl',
            field=models.CharField(blank=True, choices=[('letter', 'letter'), ('essay', 'essay')], max_length=255, null=True, verbose_name='Type of writing question'),
        ),
    ]
